#!/bin/sh

case "$1" in
    start)
        echo "Loading scull module"
        modprobe scull
        major=$(awk "\$2==\"scull\" {print \$1}" /proc/devices)
        rm -f /dev/scull[0-3]
        mknod /dev/scull0 c $major 0
        mknod /dev/scull1 c $major 1
        mknod /dev/scull2 c $major 2
        mknod /dev/scull3 c $major 3
        chmod 666 /dev/scull[0-3]
        ;;
    stop)
        echo "Unloading scull module"
        rmmod scull
        rm -f /dev/scull[0-3]
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac
exit 0
